from . import arithmetic
from . import control_flow
from . import data_transfer
from . import misc


'''
# INSTRUCTION_SET currently generated by this code
# later it should be fixed

from instructions import instruction_set
from instructions.instructions import Instruction

def is_instruction(inst):
    try:
        return issubclass(inst, Instruction) and inst != Instruction
    except TypeError:
        return False

instruction_names = []
for type_name in ['arithmetic', 'control_flow', 'data_transfer', 'misc']:
    inst_module = getattr(instruction_set, type_name)
    for inst_name in dir(inst_module):
        inst = getattr(inst_module, inst_name)
        if is_instruction(inst):
            instruction_names.append('{}.{}'.format(type_name, inst_name))

code = 'INSTRUCTION_SET = [\n'

for idx, name in enumerate(instruction_names):
    code += '    (0x{:02X}, {}),\n'.format(idx, name)

code += ']\n'
'''


INSTRUCTION_SET = [
    (0x00, arithmetic.ADD),
    (0x01, arithmetic.DEC),
    (0x02, arithmetic.DIV),
    (0x03, arithmetic.IDIV),
    (0x04, arithmetic.IMOD),
    (0x05, arithmetic.IMUL),
    (0x06, arithmetic.INC),
    (0x07, arithmetic.MOD),
    (0x08, arithmetic.MUL),
    (0x09, arithmetic.NEG),
    (0x0A, arithmetic.SUB),
    (0x0B, control_flow.CALL),
    (0x0C, control_flow.CLI),
    (0x0D, control_flow.ENTER),
    (0x0E, control_flow.INT),
    (0x0F, control_flow.IRET),
    (0x10, control_flow.JA),
    (0x11, control_flow.JAE),
    (0x12, control_flow.JB),
    (0x13, control_flow.JBE),
    (0x14, control_flow.JE),
    (0x15, control_flow.JGE),
    (0x16, control_flow.JGT),
    (0x17, control_flow.JLE),
    (0x18, control_flow.JLT),
    (0x19, control_flow.JMP),
    (0x1A, control_flow.JNE),
    (0x1B, control_flow.JNZ),
    (0x1C, control_flow.JZ),
    (0x1D, control_flow.LEAVE),
    (0x1E, control_flow.RET),
    (0x1F, control_flow.RETPOP),
    (0x20, control_flow.SETINT),
    (0x21, control_flow.STI),
    (0x22, data_transfer.IN),
    (0x23, data_transfer.MOV),
    (0x24, data_transfer.OUT),
    (0x25, data_transfer.POP),
    (0x26, data_transfer.POPF),
    (0x27, data_transfer.PUSH),
    (0x28, data_transfer.PUSHF),
    (0x29, misc.HLT),
    (0x2A, misc.NOP),
    (0x2B, misc.PRINT),
    (0x2C, misc.PRINTCHAR),
    (0x2D, misc.SETTMR),
    (0x2E, misc.SHUTDOWN),
]
